# Generated by Django 5.0.4 on 2024-05-05 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fatmugapp', '0006_alter_historicalperformance_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorPurchaseOrderMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_id', models.IntegerField()),
                ('po_id', models.CharField(max_length=255)),
                ('order_date', models.DateTimeField()),
                ('delivery_date', models.DateTimeField()),
                ('status', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='historicalperformance',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
