# Generated by Django 5.0.4 on 2024-05-05 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fatmugapp', '0007_vendorpurchaseordermetrics_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VendorPurchaseOrderMetrics',
        ),
    ]
