# Generated by Django 5.0.4 on 2024-05-06 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fatmugapp', '0008_delete_vendorpurchaseordermetrics'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrderDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_date', models.DateTimeField()),
                ('status', models.CharField(max_length=100)),
                ('actual_delivery_date', models.DateTimeField(blank=True, null=True)),
                ('po', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fatmugapp.purchaseorder')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fatmugapp.vendor')),
            ],
        ),
    ]
